insert into directores(nombre, genero, premios, fechaNacimiento, nacionalidad, descripcion, idPelicula, srcImagen) 
values ("Fincher", "Masculino","Premios de la Academia (Oscar):6 nominaciones","1962-08-08", "estadounidense", "David Fincher es un renombrado director, productor y guionista de cine estadounidense conocido por su estilo distintivo y su habilidad para crear películas visualmente impactantes y narrativamente complejas. Nacido el 28 de agosto de 1962 en Denver, Colorado, Fincher comenzó su carrera en la industria cinematográfica trabajando en efectos visuales y dirigiendo videos musicales para artistas como Madonna y Aerosmith.","1", "./img/directores/finxer.jpg");
insert into directores(nombre, genero, premios, fechaNacimiento, nacionalidad, descripcion, idPelicula, srcImagen) 
values ("Tarantino", "Masculino", "Premios de la Academia (Oscar): 2 victorias, 7 nominaciones", "1963-03-27", "estadounidense", "Quentin Tarantino es un aclamado director, guionista y productor de cine estadounidense conocido por su estilo único y su pasión por el cine. Nació el 27 de marzo de 1963 en Knoxville, Tennessee. Tarantino es famoso por su diálogo ingenioso, su narrativa no lineal y su homenaje al cine de género. Ha dirigido películas icónicas como Pulp Fiction, Kill Bill y Bastardos sin Gloria.", "2", "./img/directores/tarantin.jpg");
insert into directores(nombre, genero, premios, fechaNacimiento, nacionalidad, descripcion, idPelicula, srcImagen) 
values ("Anderson", "Masculino", "Premios de la Academia (Oscar): 4 nominaciones", "1969-05-01", "estadounidense", "Wes Anderson es un reconocido director, guionista y productor de cine estadounidense conocido por su estilo visualmente distintivo y sus narrativas peculiares. Nació el 1 de mayo de 1969 en Houston, Texas. Anderson es famoso por sus meticulosos diseños de producción, sus paletas de colores vibrantes y su enfoque idiosincrásico hacia la comedia y el drama. Ha dirigido películas aclamadas como The Grand Budapest Hotel, The Royal Tenenbaums y Moonrise Kingdom.", "3", "./img/directores/wes.jpg");

insert into peliculas(nombre, genero, sinapsis, fechaEstreno, duracion, presupuesto, recaudacion, srcImagen) 
values ("El Club de la Lucha", "Drama", "Un oficinista insomne y un carismático vendedor de jabón crean un club de lucha clandestino que se convierte en algo mucho más grande de lo que jamás habían imaginado.", "1999-10-15", "139 minutos", "$63 millones", "$101 millones", "./img/peliculas/clublucha.jpg");
insert into peliculas(nombre, genero, sinapsis, fechaEstreno, duracion, presupuesto, recaudacion, srcImagen) 
values ("Pulp Fiction", "Drama/Crimen", "Pulp Fiction sigue las historias interrelacionadas de dos asesinos a sueldo, un boxeador, un gángster y su esposa, y un par de ladrones de restaurantes, en el oscuro y violento mundo del crimen de Los Ángeles.", "1994-10-14", "154 minutos", "$8.5 millones", "$213.9 millones", "./img/peliculas/pulpfic.jpg");
insert into peliculas(nombre, genero, sinapsis, fechaEstreno, duracion, presupuesto, recaudacion, srcImagen) 
values ("El Gran Hotel Budapest", "Comedia/Drama", "La película sigue las aventuras de un legendario conserje de un famoso hotel europeo y el joven empleado que se convierte en su protegido. Juntos se ven envueltos en el robo de una valiosa pintura durante la convulsa época entre guerras.", "2014-03-28", "100 minutos", "$25 millones", "$174.8 millones", "./img/peliculas/hotelbudapest.jpg");

use fnc;
/*ACTORES INSERTADOS*/
INSERT INTO actores(nombre,genero,premios,fechaNacimiento,nacionalidad,descripcion,srcImagen)
VALUES
("Marlon Brando", "Masculino","Premios de la Academia (Oscar): 2 premios y 8 nominaciones", "1924-01-01", "estadounidense", "Marlon Brando fue un icónico actor estadounidense nacido el 3 de abril de 1924 en Omaha, Nebraska, y fallecido el 1 de julio de 2004 en Los Ángeles, California. Reconocido por su talento natural, carisma magnético y estilo único de actuación, Brando es considerado uno de los actores más influyentes en la historia del cine. Su carrera abarcó más de cinco décadas y dejó un legado imborrable en la industria cinematográfica. Brando se destacó por su capacidad para sumergirse en los personajes que interpretó, a menudo desafiando las convenciones establecidas y rompiendo moldes en su búsqueda de autenticidad y realismo.", "/img/premios/MejorPremiosGlobos/brandom.jpg");

INSERT INTO actores(nombre,genero,premios,fechaNacimiento,nacionalidad,descripcion,srcImagen)
VALUES
("Al pacino", "Masculino","Globos de Oro: 5 premios y 20 nominaciones", "1940-02-02", "estadounidense", 'Al Pacino es un renombrado actor estadounidense nacido el 25 de abril de 1940 en Nueva York. Es reconocido por su talento versátil y su capacidad para interpretar una amplia gama de personajes con profundidad y autenticidad. Ganador de múltiples premios, incluyendo un Premio de la Academia por su actuación en "Scent of a Woman" (1992), Pacino ha dejado una huella indeleble en la industria del cine y el teatro. Su carrera abarca décadas y ha participado en icónicas películas como "The Godfather" (El Padrino), "Scarface", "Heat" y "Dog Day Afternoon". Además de su éxito en la pantalla grande, Pacino ha tenido una destacada trayectoria en el teatro, actuando en producciones tanto en Broadway como en el West End de Londres. Su carisma, intensidad y dedicación lo convierten en una figura legendaria en el mundo del entretenimiento.', "/img/premios/MejorPremiosGlobos/alpa.jpg");

INSERT INTO actores(nombre,genero,premios,fechaNacimiento,nacionalidad,descripcion,srcImagen)
VALUES
("Robert Duvall", "Masculino","Premios de la Academia (Oscar): 1 premio y 7 nominaciones", "1931-03-03", "estadounidense", 'Robert Duvall es un actor estadounidense nacido el 5 de enero de 1931 en San Diego, California. Es reconocido por su versatilidad y habilidad para interpretar una amplia gama de personajes en cine y televisión. Duvall ha participado en numerosas películas aclamadas, incluyendo "El Padrino" (en la que interpretó a Tom Hagen), "Apocalypse Now", "Tender Mercies" (por la cual ganó el premio Oscar al Mejor Actor), "El Juez", entre otras. Su talento ha sido reconocido con múltiples premios y nominaciones a lo largo de su carrera, convirtiéndolo en una figura icónica de la actuación en Hollywood.
', "/img/premios/MejorPremiosGlobos/duvall.jpg");

select * from actores;
/*PRODUCTORES INSERTADOS*/
INSERT INTO productores (nombre, genero, premios, fechaNacimiento, nacionalidad, descripcion, srcImagen) 
VALUES ('Steven Spielberg', 'Masculino', 'Premios de la Academia (Oscar): \n3 premios y 23 nominaciones \n\nGlobos de Oro: \n10 premios y 33 nominaciones \n\nBAFTA: \n2 premios y 17 nominaciones \n\nCannes Film Festival: \n1 premio y 2 nominaciones', '1946-12-18', 'Estados Unidos', 'Steven Spielberg es uno de los directores de cine más influyentes y exitosos de la historia del cine. Nacido el 18 de diciembre de 1946 en Cincinnati, Ohio, Estados Unidos, Spielberg ha dejado una marca indeleble en la industria cinematográfica con su habilidad para contar historias cautivadoras y su destreza técnica. Es conocido por una amplia gama de películas que abarcan diferentes géneros, desde aventuras épicas como "Jurassic Park" y "Indiana Jones", hasta dramas emotivos como "La lista de Schindler" y "Salvar al soldado Ryan". Su estilo distintivo se caracteriza por una narración visualmente impactante y una capacidad para crear personajes memorables. Ha sido nominado en múltiples ocasiones para los premios más prestigiosos de la industria, y ha ganado numerosos Oscars, incluido el premio a Mejor Director por "La lista de Schindler". Además de dirigir, Spielberg ha producido una gran cantidad de películas exitosas a través de su compañía productora, Amblin Entertainment.', '/img/directores/stiven.jpg');

INSERT INTO productores (nombre, genero, premios, fechaNacimiento, nacionalidad, descripcion, srcImagen) 
VALUES ('Christopher Nolan', 'Masculino', 'Premios de la Academia (Oscar): \n8 nominaciones \n\nGlobos de Oro: \n2 premios y 9 nominaciones \n\nBAFTA: \n8 nominaciones \n\nPremios David di Donatello (Italia) \n1 premio y 2 nominaciones', '1970-07-30', 'Reino Unido', 'Christopher Nolan es un aclamado director, guionista y productor de cine británico. Nacido el 30 de julio de 1970 en Londres, Inglaterra, Nolan es conocido por su estilo distintivo y su habilidad para crear películas innovadoras que desafían las convenciones narrativas y exploran conceptos complejos. Sus obras a menudo incorporan elementos de la ciencia ficción, el suspenso y la filosofía. Nolan alcanzó reconocimiento internacional con películas como "Memento" (2000), una historia enrevesada contada en orden inverso, y "El Origen" (2010), un thriller psicológico que explora el mundo de los sueños y la realidad. Sin embargo, su mayor éxito comercial llegó con la trilogía de Batman, que incluye "Batman Begins" (2005), "The Dark Knight" (2008) y "The Dark Knight Rises" (2012). Estas películas revitalizaron el género de superhéroes y fueron elogiadas tanto por la crítica como por el público.', '/img/directores/nolan.jpg');

INSERT INTO productores (nombre, genero, premios, fechaNacimiento, nacionalidad, descripcion, srcImagen) 
VALUES ('Quentin Tarantino', 'Masculino', 'Premios de la Academia (Oscar): \n2 premios y 11 nominaciones \n\nGlobos de Oro: \n4 premios y 23 nominaciones \n\nFestival de Cannes: \n1 premio y 5 nominaciones \n\nPremios BAFTA: \n2 premios y 11 nominaciones \n\nPremios Emmy: \n1 premio y 11 nominaciones', '1963-03-27', 'Estados Unidos', 'Quentin Tarantino es un destacado cineasta, guionista y actor estadounidense, conocido por su estilo único y distintivo en la dirección de películas. Nacido el 27 de marzo de 1963 en Knoxville, Tennessee, Tarantino comenzó su carrera en la industria cinematográfica como empleado en una tienda de alquiler de videos, donde desarrolló su pasión por el cine. Es reconocido por su habilidad para combinar géneros cinematográficos, diálogos ingeniosos y referencias culturales en sus obras. Su estilo se caracteriza por su violencia estilizada, narrativas no lineales y una predilección por la música pop retro en la banda sonora. Algunas de sus películas más famosas incluyen "Pulp Fiction", que le valió el premio Óscar al Mejor Guion Original en 1995, así como "Kill Bill", "Reservoir Dogs", "Inglourious Basterds", "Django Unchained" y "Once Upon a Time in Hollywood".', '/img/directores/tarantin.jpg');

INSERT INTO productores (nombre, genero, premios, fechaNacimiento, nacionalidad, descripcion, srcImagen) 
VALUES ('Michael Bay', 'Masculino', 'Premios Razzie: \n3 premios y 16 nominaciones', '1965-02-17', 'Estados Unidos', 'Michael Bay es un director de cine y productor conocido por su estilo visual extravagante y su enfoque en películas de acción de gran presupuesto. Nacido el 17 de febrero de 1965 en Los Ángeles, California, Bay se destacó en la industria cinematográfica por su habilidad para crear secuencias de acción espectaculares y efectos visuales impactantes. Es famoso por dirigir películas como "Armageddon", "Transformers" y "Pearl Harbor", que son conocidas por su ritmo frenético, explosiones espectaculares y escenas de acción intensas. Aunque sus películas han sido criticadas por su énfasis en el espectáculo sobre la narrativa, Bay ha demostrado ser un director comercialmente exitoso con una base de fans leales.', '/img/directores/bay.jpg');


select * from peliculas;
